export const GLOSSARY: Record<string, string> = {
  // Common UI & Status
  merchant_preorders: "ကြိုတင်မှာယူမှုများ",
  merchant_disputes: "အငြင်းပွားမှုများ",
  farmer: "လယ်သမား",
  merchant: "ကုန်သည်",
  wholesaler: "လက်ကားရောင်းချသူ",
  retailer: "လက်လီရောင်းချသူ",
  seeds: "မျိုးစေ့များ",
  crops: "သီးနှံများ",
  fertilizer: "ဓာတ်မြေဩဇာ",
  mmk: "ကျပ်",
  rainy: "မိုးရာသီ",
  summer: "နွေရာသီ",
  winter: "ဆောင်းရာသီ",
  rice: "ဆန်/စပါး",
  beans: "ပဲမျိုးစုံ",
  tin: "တင်း",
  bag: "အိတ်",
  mandalay: "မန္တလေး",
  "yangon (bayintnaung)": "ရန်ကုန် (ဘုရင့်နောင်)",
  income: "ဝင်ငွေ",
  expense: "အသုံးစရိတ်",
  labor: "အလုပ်သမား",
  machinery: "စက်ပစ္စည်း",

  // NRC Status & Name Prefixes
  "(n)": "နိုင်",
  naing: "နိုင်",
  pyu: "ပြု",
  ee: "ဧ",
  u: "ဦး",
  daw: "ဒေါ်",
  ko: "ကို",
  maung: "မောင်",
  ma: "မ",

  // Common Name Syllables (One word mapping)
  aung: "အောင်",
  kyaw: "ကျော်",
  min: "မင်း",
  hla: "လှ",
  tun: "ထွန်း",
  zaw: "ဇော်",
  win: "ဝင်း",
  soe: "စိုး",
  aye: "အေး",
  hsu: "စု",
  mya: "မြ",
  khin: "ခင်",
  cho: "ချို",
  thida: "သီတာ",
  nilar: "နီလာ",
  phyu: "ဖြူ",
  kyi: "ကြည်",
  nu: "နု",
  thein: "သိန်း",
  htet: "ထက်",
  zin: "ဇင်",
  myat: "မြတ်",
  thu: "သူ",
  wai: "ဝေ",
  lin: "လင်း",
  lwin: "လွင်",
  hein: "ဟိန်း",
  san: "ဆန်း",
  phyo: "ဖြိုး",
  htun: "ထွန်း",
  mahar: "မဟာ",
  thitsar: "သစ္စာ",
  myo: "မျိုး",
  mi: "မိ",
  thon: "သုံး",
  ba: "ဗ",
  gyi: "ကြီး",
  kaung: "ကောင်း",

  // Time Markers (AM/PM)
  am: "နံနက်",
  pm: "ညနေ",

  // Days
  saturday: "စနေနေ့",
  sunday: "တနင်္ဂနွေနေ့",
  monday: "တနင်္လာနေ့",
  tuesday: "အင်္ဂါနေ့",
  wednesday: "ဗုဒ္ဓဟူးနေ့",
  thursday: "ကြာသပတေးနေ့",
  friday: "သောကြာနေ့",

  // Months
  january: "ဇန်နဝါရီ",
  february: "ဖေဖော်ဝါရီ",
  march: "မတ်",
  april: "ဧပြီ",
  may: "မေ",
  june: "ဇွန်",
  july: "ဇူလိုင်",
  august: "ဩဂုတ်",
  september: "စက်တင်ဘာ",
  october: "အောက်တိုဘာ",
  november: "နိုဝင်ဘာ",
  december: "ဒီဇင်ဘာ",
  jan: "ဇန်နဝါရီ",
  feb: "ဖေဖော်ဝါရီ",
  mar: "မတ်",
  apr: "ဧပြီ",
  jun: "ဇွန်",
  jul: "ဇူလိုင်",
  aug: "ဩဂုတ်",
  sep: "စက်တင်ဘာ",
  oct: "အောက်တိုဘာ",
  nov: "နိုဝင်ဘာ",
  dec: "ဒီဇင်ဘာ",

  // Crop Names
  pawsanyin: "ပေါ်ဆန်းရင်",
  shwepyipawsan: "ရွှေဘိုပေါ်ဆန်း",
  sinthuka: "ဆင်သုခ",
  matpe: "မတ်ပဲ",
  peditsein: "ပဲတီစိမ်း",
  penilay: "ပဲနီလေး",
  manothuka: "မနောသုခ",
  "yet 90": "ရက် ၉၀",
  sichosan: "ဆီချိုဆန်း",
  pawsanmwe: "ပေါ်ဆန်းမြွှေး",
  pakhanshwewa: "ပခန်းရွှေဝါ",
  kauknyinsan: "ကောက်ညှင်းဆန်",
  lonethwaymwe: "လုံးသွယ်မြွှေး",
  pawsangyi: "ပေါ်ဆန်းကြီး",
  pawsanlat: "ပေါ်ဆန်းလတ်",
  thihtatyin: "သီးထပ်ရင်",
  shwethway: "ရွှေသွယ်",
  meekauk: "မီးကောက်",
  pegyi: "ပဲကြီး",
  sadawpe: "စားတော်ပဲ",

  // Regions & States
  "ayeyarwady region": "ဧရာဝတီတိုင်းဒေသကြီး",
  "bago region": "ပဲခူးတိုင်းဒေသကြီး",
  "chin state": "ချင်းပြည်နယ်",
  "kachin state": "ကချင်ပြည်နယ်",
  "kayah state": "ကယားပြည်နယ်",
  "kayin state": "ကရင်ပြည်နယ်",
  "magway region": "မကွေးတိုင်းဒေသကြီး",
  "mandalay region": "မန္တလေးတိုင်းဒေသကြီး",
  "mon state": "မွန်ပြည်နယ်",
  "rakhine state": "ရခိုင်ပြည်နယ်",
  "sagaing region": "စစ်ကိုင်းတိုင်းဒေသကြီး",
  "shan state": "ရှမ်းပြည်နယ်",
  "tanintharyi region": "တနင်္သာရီတိုင်းဒေသကြီး",
  "yangon region": "ရန်ကုန်တိုင်းဒေသကြီး",
  naypyidaw: "နေပြည်တော်",

  // Districts
  "pathein district": "ပုသိမ်ခရိုင်",
  "hinthada district": "ဟင်္သာတခရိုင်",
  "myaungmya district": "မြောင်းမြခရိုင်",
  "pyapon district": "ဖျာပုံခရိုင်",
  "maubin district": "မအူပင်ခရိုင်",
  "labutta district": "လပွတ္တာခရိုင်",
  "bago district": "ပဲခူးခရိုင်",
  "toungoo district": "တောင်ငူခရိုင်",
  "pyay district": "ပြည်ခရိုင်",
  "tharrawaddy district": "သာယာဝတီခရိုင်",
  "falam district": "ဖလမ်းခရိုင်",
  "hakha district": "ဟားခါးခရိုင်",
  "matupi district": "မတူပီခရိုင်",
  "mindat district": "မင်းတပ်ခရိုင်",
  "paletwa district": "ပလက်ဝခရိုင်",
  "myitkyina district": "မြစ်ကြီးနားခရိုင်",
  "bhamo district": "ဗန်းမော်ခရိုင်",
  "mohnyin district": "မိုးညှင်းခရိုင်",
  "putao district": "ပူတာအိုခရိုင်",
  "chipwi district": "ချီဖွေခရိုင်",
  "tanai district": "တနိုင်းခရိုင်",
  "loikaw district": "လွိုင်ကော်ခရိုင်",
  "bawlakhe district": "ဘောလခဲခရိုင်",
  "hpa-an district": "ဘားအံခရိုင်",
  "myawaddy district": "မြဝတီခရိုင်",
  "kawkareik district": "ကော့ကရိတ်ခရိုင်",
  "kyainseikgyi district": "ကြာအင်းဆိပ်ကြီးခရိုင်",
  "hpapun district": "ဖာပွန်ခရိုင်",
  "thandaunggyi district": "သံတောင်ကြီးခရိုင်",
  "magway district": "မကွေးခရိုင်",
  "minbu (sagu) district": "မင်းဘူးခရိုင်",
  "thayet district": "သရက်ခရိုင်",
  "pakokku district": "ပခုက္ကူခရိုင်",
  "gangaw district": "ဂန့်ဂေါခရိုင်",
  "mandalay district": "မန္တလေးခရိုင်",
  "pyin oo lwin district": "ပြင်ဦးလွင်ခရိုင်",
  "kyaukse district": "ကျောက်ဆည်ခရိုင်",
  "myingyan district": "မြင်းခြံခရိုင်",
  "nyaung-u district": "ညောင်ဦးခရိုင်",
  "meiktila district": "မိတ္ထီလာခရိုင်",
  "yamethin district": "ရမည်းသင်းခရိုင်",
  "mawlamyine district": "မော်လမြိုင်ခရိုင်",
  "thaton district": "သထုံခရိုင်",
  "kyaikto district": "ကျိုက်ထိုခရိုင်",
  "ye district": "ရေးခရိုင်",
  "maungdaw district": "မောင်တောခရိုင်",
  "sittwe district": "စစ်တွေခရိုင်",
  "mrauk-u district": "မြောက်ဦးခရိုင်",
  "kyaukpyu district": "ကျောက်ဖြူခရိုင်",
  "thandwe district": "သံတွဲခရိုင်",
  "sagaing district": "စစ်ကိုင်းခရိုင်",
  "monywa district": "မုံရွာခရိုင်",
  "shwebo district": "ရွှေဘိုခရိုင်",
  "katha district": "ကသာခရိုင်",
  "kalay district": "ကလေးခရိုင်",
  "mawlaik district": "မော်လိုက်ခရိုင်",
  "tamu district": "တမူးခရိုင်",
  "taunggyi district": "တောင်ကြီးခရိုင်",
  "kalaw district": "ကလောခရိုင်",
  "loilen district": "လွိုင်လင်ခရိုင်",
  "nansang district": "နမ့်စန်ခရိုင်",
  "mong shu district": "မိုင်းရှူးခရိုင်",
  "langkho district": "လင်းခေးခရိုင်",
  "lashio district": "လားရှိုးခရိုင်",
  "tangyan district": "တန့်ယန်းခရိုင်",
  "laukkaing district": "လောက်ကိုင်ခရိုင်",
  "muse district": "မူဆယ်ခရိုင်",
  "kutkai district": "ကွတ်ခိုင်ခရိုင်",
  "kyaukme district": "ကျောက်မဲခရိုင်",
  "momeik district": "မိုးမိတ်ခရိုင်",
  "hopang district": "ဟိုပန်ခရိုင်",
  "kengtung district": "ကျိုင်းတုံခရိုင်",
  "tachileik district": "တာချီလိတ်ခရိုင်",
  "mong yang district": "မိုင်းယန်းခရိုင်",
  "dawei district": "ထားဝယ်ခရိုင်",
  "myeik district": "မြိတ်ခရိုင်",
  "kawthoung district": "ကော့သောင်းခရိုင်",
  "yangon district": "ရန်ကုန်ခရိုင်",
  "insein district": "အင်းစိန်ခရိုင်",
  "hlegu district": "လှည်းကူးခရိုင်",
  "mingaladon district": "မင်္ဂလာဒုံခရိုင်",
  "thanlyin district": "သန်လျင်ခရိုင်",
  "twantay district": "တွံတေးခရိုင်",
  "ottara district": "ဥတ္တရခရိုင်",
  "dekkhina district": "ဒက္ခိဏခရိုင်",

  // Townships
  pathein: "ပုသိမ်",
  thabaung: "သာပေါင်း",
  ngapudaw: "ငပုတော",
  kangyidaunt: "ကန်ကြီးထောင့်",
  kyaunggon: "ကျောင်းကုန်း",
  yegyi: "ရေကြည်",
  hinthada: "ဟင်္သာတ",
  zalun: "ဇလွန်",
  lemyethna: "လေးမျက်နှာ",
  myanaung: "မြန်အောင်",
  myaungmya: "မြောင်းမြ",
  einme: "အိမ်မဲ",
  wakema: "ဝါးခယ်မ",
  pyapon: "ဖျာပုံ",
  bogale: "ဘိုကလေး",
  kyaiklat: "ကျိုက်လတ်",
  dedaye: "ဒေးဒရဲ",
  maubin: "မအူပင်",
  pantanaw: "ပန်းတနော်",
  nyaungdon: "ညောင်တုန်း",
  danubyu: "ဓနုဖြူ",
  mawlamyinegyun: "မော်လမြိုင်ကျွန်း",
  bago: "ပဲခူး",
  kawa: "ကဝ",
  thanatpin: "သနပ်ပင်",
  waw: "ဝေါ",
  "daik-u": "ဒိုက်ဦး",
  kyauktaga: "ကျောက်တံခါး",
  toungoo: "တောင်ငူ",
  yedashe: "ရေတာရှည်",
  kyaukkyi: "ကျောက်ကြီး",
  // phyu: "ဖြူး",
  okpho: "အုတ်ဖို",
  pyay: "ပြည်",
  padaung: "ပန်းတောင်း",
  paukkhaung: "ပေါက်ခေါင်း",
  thegon: "သဲကုန်း",
  tharrawaddy: "သာယာဝတီ",
  minhla: "မင်းလှ",
  letpadan: "လက်ပံတန်း",
  zigon: "ဇီကုန်း",
  nattalin: "နတ္တလင်း",
  monyo: "မုံရွာ",
  falam: "ဖလမ်း",
  tiddim: "တီးတိန်",
  hakha: "ဟားခါး",
  thantlang: "ထန်တလန်",
  matupi: "မတူပီ",
  rezua: "ရေဇွာ",
  mindat: "မင်းတပ်",
  kanpetlet: "ကန်ပက်လက်",
  paletwa: "ပလက်ဝ",
  myitkyina: "မြစ်ကြီးနား",
  waingmaw: "ဝိုင်းမော်",
  injangyang: "အင်ဂျန်းယန်",
  tanai: "တနိုင်း",
  bhamo: "ဗန်းမော်",
  mansi: "မန်စီ",
  momauk: "မိုးမောက်",
  shwegu: "ရွှေကူ",
  mohnyin: "မိုးညှင်း",
  mogaung: "မိုးကောင်း",
  phakant: "ဖားကန့်",
  putao: "ပူတာအို",
  sumprabum: "ဆွမ်ပရာဘွမ်",
  machanbaw: "မချမ်းဘော",
  khaunglanhpu: "ခေါင်လန်ဖူး",
  nawngmun: "နောင်မွန်း",
  chipwi: "ချီဖွေ",
  tsawlaw: "ဆော့လော်",
  loikaw: "လွိုင်ကော်",
  demoso: "ဒီမောဆို",
  hpruso: "ဖရူဆို",
  shadaw: "ရှားတော",
  bawlakhe: "ဘောလခဲ",
  hpasawng: "ဖားဆောင်း",
  mese: "မယ်စဲ့",
  "hpa-an": "ဘားအံ",
  hlaingbwe: "လှိုင်းဘွဲ့",
  myawaddy: "မြဝတီ",
  kawkareik: "ကော့ကရိတ်",
  kyainseikgyi: "ကြာအင်းဆိပ်ကြီး",
  hpapun: "ဖာပွန်",
  thandaunggyi: "သံတောင်ကြီး",
  yenangyaung: "ရေနံချောင်း",
  chauk: "ချောက်",
  taungdwingyi: "တောင်တွင်းကြီး",
  myaing: "မြိုင်",
  minbu: "မင်းဘူး",
  sagu: "စကု",
  pwintbyu: "ပွင့်ဖြူ",
  ngape: "ငဖဲ",
  thayet: "သရက်",
  aunglan: "အောင်လံ",
  sinbaungwe: "ဆင်ပေါင်ဝဲ",
  pakokku: "ပခုက္ကူ",
  yesagyo: "ရေစကြို",
  pauk: "ပေါက်",
  gangaw: "ဂန့်ဂေါ",
  htilin: "ထီးလင်း",
  saw: "စော",
  aungmyethazan: "အောင်မြေသာစံ",
  chanayethazan: "ချမ်းအေးသာစံ",
  mahaaungmye: "မဟာအောင်မြေ",
  chanmyathazi: "ချမ်းမြသာစည်",
  pyigyidagun: "ပြည်ကြီးတံခွန်",
  amarapura: "အမရပူရ",
  patheingyi: "ပုသိမ်ကြီး",
  madaya: "မတ္တရာ",
  singu: "စဉ့်ကူး",
  mogok: "မိုးကုတ်",
  thabeikkyin: "သပိတ်ကျင်း",
  kyaukse: "ကျောက်ဆည်",
  "tada-u": "တံတားဦး",
  myittha: "မြစ်သား",
  sintgaing: "စဉ့်ကိုင်",
  myingyan: "မြင်းခြံ",
  taungtha: "တောင်သာ",
  natogyi: "နွားထိုးကြီး",
  ngazun: "ငါန်းဇွန်",
  "nyaung-u": "ညောင်ဦး",
  kyaukpadaung: "ကျောက်ပန်းတောင်း",
  meiktila: "မိတ္ထီလာ",
  mahlaing: "မလှိုင်",
  thazi: "သာစည်",
  wundwin: "ဝမ်းတွင်း",
  yamethin: "ရမည်းသင်း",
  pyawbwe: "ပျော်ဘွယ်",
  mawlamyine: "မော်လမြိုင်",
  kyaikmarraw: "ကျိုက်မရော",
  chaungzon: "ချောင်းဆုံ",
  mudon: "မုဒုံ",
  thaton: "သထုံ",
  paung: "ပေါင်",
  kyaikto: "ကျိုက်ထို",
  bilin: "ဘီးလင်း",
  ye: "ရေး",
  thanbyuzayat: "သံဖြူဇရပ်",
  maungdaw: "မောင်တော",
  buthidaung: "ဘူးသီးတောင်",
  sittwe: "စစ်တွေ",
  pauktaw: "ပေါက်တော",
  ponnagyun: "ပုဏ္ဏားကျွန်း",
  rathedaung: "ရသေ့တောင်",
  "mrauk-u": "မြောက်ဦး",
  kyauktaw: "ကျောက်တော်",
  minbya: "မင်းပြား",
  myebon: "မြေပုံ",
  kyaukpyu: "ကျောက်ဖြူ",
  ann: "အမ်း",
  manaung: "မာန်အောင်",
  ramree: "ရမ်းဗြဲ",
  thandwe: "သံတွဲ",
  gwa: "ဂွ",
  toungup: "တောင်ကုတ်",
  sagaing: "စစ်ကိုင်း",
  mingin: "မင်းကင်း",
  myaung: "မြောင်",
  budalin: "ဘုတလင်",
  ayadaw: "အရာတော်",
  "chaung-u": "ချောင်းဦး",
  shwebo: "ရွှေဘို",
  tabayin: "ဒီပဲယင်း",
  "khin-u": "ခင်ဦး",
  wetlet: "ဝက်လက်",
  taze: "တန့်ဆည်",
  katha: "ကသာ",
  indaw: "အင်းတော်",
  banmauk: "ဗန်းမောက်",
  tigyaing: "ထီးချိုင့်",
  kalay: "ကလေး",
  kalewa: "ကလေးဝ",
  mawlaik: "မော်လိုက်",
  paungbyin: "ဖောင်းပြင်",
  tamu: "တမူး",
  khampat: "ခမ်းပတ်",
  taunggyi: "တောင်ကြီး",
  lawksawk: "ရပ်စောက်",
  kalaw: "ကလော",
  nyaungshwe: "ညောင်ရွှေ",
  pekon: "ဖယ်ခုံ",
  loilen: "လွိုင်လင်",
  "lai-hka": "လဲချား",
  "mong kaung": "မိုင်းကိုင်",
  nansang: "နမ့်စန်",
  kunhing: "ကွန်ဟိန်း",
  mone: "မိုးနဲ",
  "mong shu": "မိုင်းရှူး",
  "mong hsat": "မိုင်းဆတ်",
  langkho: "လင်းခေး",
  "mong pan": "မိုင်းပန်",
  mawkmai: "မောက်မယ်",
  lashio: "လားရှိုး",
  hsenwi: "သိန္နီ",
  kunlong: "ကွမ်းလုံ",
  tangyan: "တန့်ယန်း",
  "mong yai": "မိုင်းရယ်",
  laukkaing: "လောက်ကိုင်",
  muse: "မူဆယ်",
  namhkam: "နမ့်ခမ်း",
  kutkai: "ကွတ်ခိုင်",
  kyaukme: "ကျောက်မဲ",
  nawnghkio: "နောင်ချို",
  hsipaw: "သီပေါ",
  namtu: "နမ့်တူ",
  momeik: "မိုးမိတ်",
  mabein: "မဘိမ်း",
  hopang: "ဟိုပန်",
  panwaun: "ပန်ဝိုင်",
  mongmau: "မိုင်းမော",
  kengtung: "ကျိုင်းတုံ",
  "mong khet": "မိုင်းခတ်",
  "mong ping": "မိုင်းပျင်း",
  tachileik: "တာချီလိတ်",
  "mong hpayak": "မိုင်းဖြတ်",
  "mong yang": "မိုင်းယန်း",
  dawei: "ထားဝယ်",
  launglon: "လောင်းလုံး",
  thayetchaung: "သရက်ချောင်း",
  yebyu: "ရေဖြူ",
  myeik: "မြိတ်",
  kyunsu: "ကျွန်းစု",
  palaw: "ပုလော",
  kawthoung: "ကော့သောင်း",
  bokpyin: "ဘုတ်ပြင်း",
  thaketa: "သာကေတ",
  "north dagon": "ဒဂုံမြို့သစ်မြောက်ပိုင်း",
  "south dagon": "ဒဂုံမြို့သစ်တောင်ပိုင်း",
  "east dagon": "ဒဂုံမြို့သစ်အရှေ့ပိုင်း",
  "west dagon": "ဒဂုံမြို့သစ်အနောက်ပိုင်း",
  "south okkalapa": "တောင်ဥက္ကလာပ",
  "north okkalapa": "မြောက်ဥက္ကလာပ",
  yankin: "ရန်ကင်း",
  ahlone: "အလုံ",
  lanmadaw: "လမ်းမတော်",
  latha: "လသာ",
  sanchaung: "စမ်းချောင်း",
  kamayut: "ကမာရွတ်",
  kyimyindaing: "ကြည့်မြင်တိုင်",
  mayangone: "မရမ်းကုန်း",
  pazundaung: "ပုဇွန်တောင်",
  botahtaung: "ဗိုလ်တထောင်",
  "mingala taung nyunt": "မင်္ဂလာတောင်ညွန့်",
  tamwe: "တာမွေ",
  dawbon: "ဒေါပုံ",
  thingangyun: "သင်္ဃန်းကျွန်း",
  shwepyitha: "ရွှေပြည်သာ",
  pabedan: "ပန်းဘဲတန်း",
  thanlyin: "သန်လျင်",
  hlaing: "လှိုင်",
  insein: "အင်းစိန်",
  hlaingthaya: "လှိုင်သာယာ",
  hlegu: "လှည်းကူး",
  taikkyi: "တိုက်ကြီး",
  hmawbi: "မှော်ဘီ",
  mingaladon: "မင်္ဂလာဒုံ",
  thongwa: "သုံးခွ",
  kyauktan: "ကျောက်တန်း",
  kayan: "ခရမ်း",
  cocokyun: "ကိုကိုးကျွန်း",
  twantay: "တွံတေး",
  kawhmu: "ကော့မှူး",
  kungyangon: "ကွမ်းခြံကုန်း",
  dala: "ဒလ",
  "seikgyi kanaungto": "ဆိပ်ကြီးခနောင်တို",
  ottarathiri: "ဥတ္တရသီရိ",
  pobbathiri: "ပုဗ္ဗသီရိ",
  tatkon: "တပ်ကုန်း",
  zeyarthiri: "ဇေယျာသီရိ",
  dekkhinathiri: "ဒက္ခိဏသီရိ",
  lewe: "လယ်ဝေး",
  pyinmana: "ပျဉ်းမနား",
  zabuthiri: "ဇမ္ဗူသီရိ",

  // NRC Character Codes & Unique Identifiers
  agaya: "အဂယ",
  bamana: "ဗမန",
  daphaya: "ဒဖယ",
  hapana: "ဟပန",
  kamana: "ကမန",
  khalapha: "ခလဖ",
  laghana: "လဃန",
  makhaba: "မခဘ",
  manyana: "မညန",
  makata: "မကတ",
  mamana: "မမန",
  makana: "မကန",
  namana: "နမန",
  phakana: "ဖကန",
  pataa: "ပတအ",
  yakana: "ယကန",
  sabana: "စဗန",
  salana: "စလန",
  sapaba: "ဆပဗ",
  tanana: "တနန",
  wamana: "ဝမန",
  kamata: "ကမတ",
  kapata: "ကပတ",
  malana: "မလန",
  panada: "ပနဒ",
  pawana: "ပဝန",
  sadana: "ဆဒန",
  yabaya: "ယဘယ",
  kanaima: "ကနအမ",
  balakha: "ဗလခ",
  damasa: "ဒမဆ",
  hapara: "ဟပရ",
  hapasa: "ဟပသ",
  lakana: "လကန",
  masana: "မဆန",
  phayasa: "ဖယသ",
  shadata: "သဒတ",
  yatana: "ယတန",
  phasana: "ဖဆန",
  baphana: "ဘဖန",
  bakala: "ဗကလ",
  haphana: "ဟဖန",
  halaba: "ဟလဗ",
  kakara: "ကကရ",
  kasaka: "ကသက",
  labana: "လဗန",
  mawata: "မဝတ",
  patana: "ပတန",
  thadana: "သဒန",
  walama: "ဝလမ",
  kayasa: "ကယသ",
  sayana: "သယန",
  kadata: "ကဒတ",
  falana: "ဖလန",
  hakhana: "ဟခန",
  kanapala: "ကပလ",
  matapa: "မတပ",
  matana: "မတန",
  palata: "ပလတ",
  thanthana: "ထတလ",
  tatana: "တတန",
  tazana: "တဇန",
  kakana: "ကကန",
  samana: "ဆမန",
  rakhada: "ရခဒ",
  razana: "ရဇန",
  hakana: "ဟကန",
  ahata: "အဟတ",
  batala: "ဘတလ",
  halana: "ဟလန",
  htaphana: "ထဖန",
  kalana: "ကလန",
  kalata: "ကလတ",
  kanabala: "ကဘလ",
  khatana: "ခတန",
  mathana: "မသန",
  palana: "ပလန",
  phaphana: "ဖဖန",
  sakana: "စကန",
  samaya: "သယ",
  shabatha: "ရဘန",
  tamana: "တမန",
  yabana: "ယဗန",
  ahtana: "အထန",
  kathana: "ကသန",
  nyana: "ညန",
  phapana: "ဖပန",
  wathana: "ဝသန",
  yamapa: "ယမပ",
  lashana: "လရှန",
  bathapha: "ဗသဖ",
  kawthana: "ကသန",
  kalaya: "ကလယ",
  lalana: "လလန",
  tathaya: "တသယ",
  yaphana: "ယဖန",
  khamaka: "ခမက",
  thayakha: "သယခ",
  dauka: "ဒဥက",
  kawana: "ကဝန",
  nyalana: "ညလန",
  okapala: "ဥကဖ",
  oktana: "ဥတန",
  pakhana: "ပခန",
  phayana: "ဖယန",
  natalana: "နတလ",
  zakana: "ဇကန",
  thakana: "သကန",
  agala: "အဂလ",
  chamana: "ခမန",
  gagana: "ဂဂန",
  hathala: "ထလန",
  mabana: "မဗန",
  namata: "နမတ",
  pakhaka: "ပခက",
  yanyana: "ရညန",
  naphana: "နဖန",
  tataka: "တတက",
  amara: "အမရ",
  ahmaya: "အမသ",
  chamatha: "ခရသ",
  chamathaya: "ခမသ",
  khahathana: "ခဟသ",
  mataya: "မတယ",
  mahalana: "မလှန",
  nataha: "နတဟ",
  nyatana: "ညတန",
  pabatha: "ပဗသ",
  pakhakana: "ပခက",
  pathaka: "ပသက",
  thabaka: "သဘက",
  thasana: "သစန",
  yamathana: "ရမသ",
  tadaa: "တတဥ",
  myathana: "မသန",
  pyabana: "ပျဗန",
  ngazana: "ငဇန",
  balana: "ဘလန",
  khamana: "ခမန",
  khatha: "ခသ",
  madana: "မဒန",
  thaphana: "သဖန",
  thathana: "သထန",
  yamana: "ယမန",
  kazana: "ကဇန",
  lamana: "လမန",
  khama: "ခမ",
  amana: "အမန",
  bathadata: "ဘသတ",
  gamana: "ဂမန",
  kapakana: "ကပက",
  katata: "ကတတ",
  manana: "မနန",
  mapana: "မပန",
  panyana: "ပညန",
  ratana: "ရတန",
  bahana: "ဗဟန",
  batata: "ဗတထ",
  dagana: "ဒဂန",
  dagaya: "ဒဂရ",
  dagatana: "ဒဂတ",
  dagama: "ဒဂမ",
  dakana: "ဒကန",
  dalana: "ဒလန",
  dapana: "ဒပန",
  hamaba: "ဟမဘ",
  halaga: "ဟလက",
  halatha: "ဟလသ",
  asana: "အစန",
  kakatana: "ကကတ",
  khayana: "ခယန",
  lamada: "လမတ",
  magada: "မဂဒ",
  pabata: "ပဗတ",
  pazata: "ပဇတ",
  sakhana: "စခန",
  shaphatha: "ရပသ",
  thakata: "သကတ",
  thalyana: "သလျန",
  thakhana: "သခန",
  kahana: "ကဟန",
  danapha: "ဓနဖ",
  dadaye: "ဒဒရ",
  ahmapa: "အမဖ",
  hathata: "ဟသတ",
  agapa: "အဂပ",
  kaphana: "ကဖန",
  lapata: "လပတ",
  maapa: "မအပ",
  mamaka: "မမက",
  maana: "မအန",
  ngapada: "ငပတ",
  thapana: "သပန",
  wakama: "ဝခမ",
  pathana: "ပသန",
  zalana: "ဇလန",

  pending: "စောင့်ဆိုင်းဆဲ",
  confirmed: "အတည်ပြုပြီး",
  delivered: "ပို့ဆောင်ပြီး",
  cancelled: "ပယ်ဖျက်ပြီး",
  resolved: "ဖြေရှင်းပြီး",
  rejected: "ငြင်းပယ်ပြီး",
  verified: "အတည်ပြုပြီး",
  pricing: "ဈေးနှုန်းသတ်မှတ်မှု",
  payment: "ငွေပေးချေမှု",
  behavior: "အပြုအမူပိုင်းဆိုင်ရာ",
  fraud: "လိမ်လည်မှု",
  other: "အခြား",
};
